[package]
name = "keylogger"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_time = "1.1.0"
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_System_Console"] }
lazy_static = "1.5.0"
chrono = "0.4.38"